# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://alxc.net/'
baseurl: ''
title: 'Alexander Czech'
# description: 'My first try on a new website'
permalink: pretty
timezone: Europe/London
logo: "/img/logo_25.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Contact
  url: /contact/
- title: CV
  url: /cv/
- title: Projects
  url: /projects/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/img/logo_25@16px.png'
  32: '/img/logo_25@32px.png'
  96: '/img/logo_25@96px.png'
  120: '/img/logo_25@120px.png'
  144: '/img/logo_25@144px.png'
  180: '/img/logo_25@180px.png'
  512: '/img/logo_25@512px.png'
  1024: '/img/logo_25@1024px.png'

# social
social: # jekyll-seo-tag > social overrides
  name: Alexander Czech
  links:
    - https://www.linkedin.com/in/alexczech
    - https://github.com/thagorx

social_links:
  LinkedIn: https://www.linkedin.com/in/alexczech
  GitHub: https://github.com/thagorx
  email: mailto:alexander@alxc.net

# Collections
collections:
  posts:
    title: Projects
    output: true
    #description: [Projects]
    #feature_text: "##My Projects"
    feature_image: "/img/projects.jpg"
