# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://alxc.net/'
baseurl: ''
title: 'Alexander Czech'
# description: 'My first try on a new website'
permalink: pretty
# logo: ""

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Contact
  url: /contact/
- title: CV
  url: /cv/
- title: Projects
  url: /projects/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Projects
    output: true
    #description: [Projects]
    #feature_text: "##My Projects"
    feature_image: "/img/projects.jpg"
